spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/identity
    username: root
    password: besseggen
    hikari:
      maximum-pool-size: 50
      connection-timeout: 20000
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  flyway:
    enabled: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: 0oaeszrc1wEt3A0iC0h7
            client-secret: lJYdP4VtR7Das3k_hzUOiat-4_SJGGNy-Y-I9Ow7
            clientName: Okta
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
          keycloak:
            client-id: demoapp
            client-secret: demoapp
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email

        provider:
          okta:
            authorization-uri: https://dev-727816.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-727816.oktapreview.com/oauth2/v1/token
            user-info-uri: https://dev-727816.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-727816.oktapreview.com/oauth2/v1/keys
            user-name-attribute: sub
          keycloak:
            authorization-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/auth
            token-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/token
            user-info-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8000/auth/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username
